### ISSUE TITLE
Cannot create H2 database 

### ISSUE THREAD

**Issue by maxpaper86** [yoonjae0715/onlineshopping#1]
1. Background
- H2 database is being used on the sample online shopping project

2. Problem
- Cannot create H2 database

**Comment by yoonjae0715** [comment]
1. http://www.h2database.com/html/download.html - Download the last stable version

2. jdbc:h2:~/onlineshopping (run without tcp)

3. jdbc:h2:tcp://localhost/~/onlineshopping

**Comment by yoonjae0715** [comment]
Case closed
